/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RequestData {
  ipAddressPrivate?: string;
  ipAddressPublic?: string;
  name?: string;
  port?: string;
}
