export const colors = {
  CYAN: '#2CA7AF',
  BLUE: '#06607F',
  DARK: '#020D17',
  GREEN: '#364D56',
  LIGHT_GREEN: '#454C53',
  WHITE: 'white',
  LIGHT_GREY: '#F5F5F6',
  SOFT_GREY: '#E8E8E8',
  TRANSPARENT: `rgba(0,0,0,0)`,
  COLOR_SUCCESS_500: '#5aa97e',
  COLOR_SUCCESS_400: '#acd3be',
  COLOR_SUCCESS_300: '#d5e8de',
  COLOR_SUCCESS_200: '#e9f3ee',
  COLOR_SUCCESS_100: '#f3f8f6',
  COLOR_ERROR_100: '#fbf3f2',
  COLOR_ERROR_200: '#f8e9e6',
  COLOR_ERROR_300: '#f2d5cf',
  COLOR_ERROR_400: '#e7aca0',
  COLOR_ERROR_500: '#d15b43',
};

export const appColors = {
  BACKGROUND_LIGHT: colors.LIGHT_GREY,
  BACKGROUND: colors.WHITE,
  TEXT: colors.DARK,
  TEXT_LIGHT: colors.LIGHT_GREEN,
  TEXT_INVERSE: colors.WHITE,
  PRIMARY: colors.DARK,
  SECONDARY: colors.BLUE,
  ACCENT: colors.CYAN,
  FORM_BORDER: colors.LIGHT_GREEN,
  UNDERLAY: colors.LIGHT_GREY,
};
